# Generated by Django 3.1.1 on 2020-11-08 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_icon', models.ImageField(blank=True, upload_to='website/images')),
                ('apple_icon', models.ImageField(blank=True, upload_to='website/images')),
                ('logo', models.ImageField(blank=True, upload_to='website/images')),
            ],
            options={
                'verbose_name_plural': "Website's additional infomations",
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Email Addresses',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=14)),
                ('firstname', models.CharField(max_length=14)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=14)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('member', 'Member'), ('choir', 'Choir'), ('media', 'Media')], max_length=14)),
                ('photo', models.ImageField(upload_to='members/images')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('github', 'GitHub'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('whatsapp', 'WhatsApp'), ('snapchat', 'Snapchat'), ('skype', 'Skpye'), ('tik_tok', 'Tik Tok'), ('hangout', 'Hangout')], max_length=20)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_for', models.CharField(max_length=25)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WebMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webmasters', to='core.website')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_display', models.BooleanField()),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('feedback', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.additionalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='team/images')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emailaddress')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phonenumber')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.additionalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.additionalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.additionalinfo')),
            ],
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='about',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='core.textcontent'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='address',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='core.textcontent'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='mission',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='core.textcontent'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='vision',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vision', to='core.textcontent'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='core.website'),
        ),
        migrations.CreateModel(
            name='WebsiteSocialAccount',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialaccount')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.additionalinfo')),
            ],
            bases=('core.socialaccount',),
        ),
        migrations.CreateModel(
            name='WebsitePhoneNumber',
            fields=[
                ('phonenumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.phonenumber')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='core.additionalinfo')),
            ],
            bases=('core.phonenumber',),
        ),
        migrations.CreateModel(
            name='WebsiteEmailAddress',
            fields=[
                ('emailaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.emailaddress')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='core.additionalinfo')),
            ],
            bases=('core.emailaddress',),
        ),
        migrations.CreateModel(
            name='TeamMemberSocialAccount',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialaccount')),
                ('TeamMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teammember')),
            ],
            bases=('core.socialaccount',),
        ),
    ]
