# Generated by Django 3.1.1 on 2020-11-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prayerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
