# Generated by Django 3.1.1 on 2020-11-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=20, null=True),
        ),
    ]
